[package]
name = "muscedit"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.29"
winit = "0.30.3"
egui-winit = "0.29"
egui-wgpu = "0.29"
cpal = "0.15"
pollster = "0.3"
arc-swap = "1.8.2"
bytemuck = "1.25.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }

[target.'cfg(target_os = "linux")'.dependencies]
x11 = { version = "2.3", features = ["xlib"] }
