[package]
name = "esotereel_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
esotereel_lib = { package = "esotereel_lib", path = "../lib" }
rkyv = { version = "0.7.46", features = ["validation"] }
log = "0.4.29"
chrono = "0.4.44"
send_wrapper = "0.6.0"
tokio = { version = "1.51.1", features = ["full"]}
