[package]
name = "esotereel_gui_helper"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
esotereel_lib = { package = "esotereel_lib", path = "../lib" }
esotereel_core= { package = "esotereel_core", path = "../core" }
rkyv = { version = "0.7.46", features = ["validation"] }
bytecheck = "0.6"
log = "0.4.29"
tokio = { version = "1.51.1", features = ["full"]}
