[package]
name = "esotereel_gui_helper"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
esotereel_lib = { package = "esotereel_lib", path = "../lib" }
esotereel_core = { package = "esotereel_core", path = "../core" }
rkyv = { version = "0.7", features = ["validation"] }
bytecheck = "0.6"
log = "0.4"
colored = "3.0"
tokio = { version = "1", features = ["full"] }
glam = { version = "0.32", features = ["bytemuck"] }
