#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <QVector3D>
#include <QMatrix4x4>
#include <cstdint>

namespace esotereel_gui_helper {

enum class CFieldValueTag : uint32_t {
  Bool,
  Int,
  Float,
  Enum,
  String,
  Path,
  Color,
  Array,
  Map,
};

enum class CLogLevel : uint8_t {
  Off,
  Error,
  Warn,
  Info,
  Debug,
  Trace,
};

enum class CClipBindingValueTag : uint32_t {
  Static,
};

enum class SettingsFieldType {
  Bool,
  Int,
  Float,
  Enum,
  String,
  FilePath,
  Color,
  Array,
  Map,
};

enum class WrapperErrorCode {
  Ok = 0,
  NullPtr = 1,
  NotFound = 2,
  Error = 3,
  Panic = 4,
};

enum class FfiLayerRowKind {
  Layer,
  Folder,
};

enum class Direction {
  Front,
  Back,
  Top,
  Bottom,
  Left,
  Right,
};

struct ClientStateHandle;

struct Clip;

struct CommandQueue;

struct FieldValue;

struct Layer;

/// Folderの中身(名前・開閉状態・並び順)。
struct LayerFolder;

struct OffscreenTarget;

template<typename T = void>
struct Option;

struct Project;

struct RenderRowsResult;

struct Timeline;

struct WGpuUtil;

/// 手動で解放しないといけない
struct FfiOwnedString {
  uint8_t *ptr;
  uintptr_t len;
  uintptr_t capacity;
};

struct FfiResultVoid {
  bool is_ok;
  FfiOwnedString err;
};

using OptionProject = Option<Project>;

using TimelineId = uint64_t;

using LayerId = uint64_t;

using LayerFolderId = uint64_t;

struct FfiStringView {
  const uint8_t *ptr;
  uintptr_t len;
};

struct FfiOwnedStringArray {
  FfiOwnedString *ptr;
  uintptr_t len;
  uintptr_t capacity;
};

struct RgbaColor {
  float r;
  float g;
  float b;
  float a;
};

struct CFieldValue;
struct CFieldValueMapEntry;

struct CFieldValueArray {
  CFieldValue *ptr;
  uintptr_t len;
  uintptr_t capacity;
};



struct CFieldValueMap {
  CFieldValueMapEntry *ptr;
  uintptr_t len;
  uintptr_t capacity;
};

union CFieldValueData {
  uint8_t bool_value;
  int64_t int_value;
  double float_value;
  FfiOwnedString enum_value;
  FfiOwnedString string_value;
  FfiOwnedStringArray path_value;
  RgbaColor color_value;
  CFieldValueArray array_value;
  CFieldValueMap map_value;
};

struct CFieldValue {
  CFieldValueTag tag;
  CFieldValueData data;
};

struct CFieldValueMapEntry {
  FfiOwnedString key;
  CFieldValue value;
};

using OnServerReadyCFn = void(*)(bool, FfiStringView);

using LogOutCStrFn = void(*)(uintptr_t level, FfiStringView target, FfiStringView msg);

using ClipId = uint64_t;

using TimelineTick = int64_t;

union CClipBindingValueData {
  CFieldValue static_value;
};

struct CClipBindingValue {
  CClipBindingValueTag tag;
  CClipBindingValueData data;
};

template<typename T>
union FfiOptionUnion {
  T some;
};

template<typename T>
struct FfiOption {
  bool has_value;
  FfiOptionUnion<T> value;
};

template<typename T>
union FfiResultUnion {
  T ok;
  FfiOwnedString err;
};

template<typename T>
struct FfiResult {
  bool is_ok;
  FfiResultUnion<T> value;
};

using CClipBindingValueResult = FfiResult<FfiOption<CClipBindingValue>>;

struct FfiPropertySchema {
  FfiOwnedString key;
  FfiOwnedString category;
  FfiOwnedString label;
  SettingsFieldType kind_type;
  CFieldValue default_value;
};

template<typename T>
struct FfiArray {
  T *ptr;
  uintptr_t len;
  uintptr_t cap;
  /// free_fnを呼んでcから解放
  void (*free_fn)(FfiArray<T>*);
};

using FfiPropertySchemaArrayResult = FfiResult<FfiArray<FfiPropertySchema>>;

using FfiStringArrayResult = FfiResult<FfiArray<FfiOwnedString>>;

struct FfiLayerRow {
  FfiLayerRowKind node_kind;
  LayerId node_id;
  TimelineId timeline_id;
  uint32_t depth;
  bool is_folder_open;
  uint32_t clip_start;
  uint32_t clip_count;
};

struct ClipRenderInfo {
  uint64_t clip_id;
  int64_t abs_frame;
  int64_t duration;
  bool is_composite;
  bool is_open;
};

struct CameraInfo {
  QVector3D position;
  QVector3D rotation;
  bool is_orthographic;
  Direction orthographic_direction;
  float scale_factor;
  float fov;
};

using CFieldValueResult = FfiResult<FfiOption<CFieldValue>>;

/// out_state 出力パラメータを廃止し、生成したポインタ自体を戻り値として返す形に変更。
using ClientStateNewResult = FfiResult<const ClientStateHandle*>;

struct GuiCallbacks {
  void (*on_test)();
  void (*mark_dirty_timeline)(TimelineId timeline_type);
  void (*on_connected)();
};

/// out_guard 出力パラメータを廃止し、ガードの生ポインタ自体を戻り値として返す形に変更。
using ProjectLockReadResult = FfiResult<const void*>;

/// ガードからprojectポインタを取得する関数
/// out_project 出力パラメータを廃止し、ポインタ自体を戻り値として返す形に変更。
using ProjectFromGuardResult = FfiResult<const OptionProject*>;

struct FfiToolbarButton {
  FfiOwnedString id;
  FfiOwnedString label;
  FfiOwnedString tooltip;
  /// アイコン未指定なら空文字列。
  FfiOwnedString icon;
  FfiOwnedString action;
};

/// 個数取得(toolbar_get_buttons_count)+バッファ書き込み(toolbar_get_buttons)の2関数ペアを、
/// FfiArrayを直接返す1関数に統合。呼び出し側(C++)はFfiArray::free_fnで解放する。
using FfiToolbarButtonArrayResult = FfiResult<FfiArray<FfiToolbarButton>>;

/// out 出力パラメータを廃止し、生成したポインタ自体を戻り値として返す形に変更。
using WGpuUtilNewResult = FfiResult<WGpuUtil*>;

/// out 出力パラメータを廃止し、生成したポインタ自体を戻り値として返す形に変更。
using OffscreenTargetNewResult = FfiResult<OffscreenTarget*>;

using ScriptId = uint64_t;

extern "C" {

const char *get_last_err_msg();

CommandQueue *command_queue_new();

FfiResultVoid command_queue_drop(CommandQueue *ptr);

FfiResultVoid command_queue_send_all(CommandQueue *ptr_queue, const ClientStateHandle *ptr_state);

FfiResultVoid req_cmd_clip_move_mul(CommandQueue *ptr_queue,
                                    const OptionProject *ptr_opt_project,
                                    TimelineId timeline_id,
                                    const uint64_t *ptr,
                                    uintptr_t len,
                                    int64_t position_moved,
                                    int64_t duration_added,
                                    intptr_t layer_moved);

/// be careful of deadlock
FfiResultVoid req_cmd_add_clip_dummy(CommandQueue *ptr_queue,
                                     const ClientStateHandle *ptr_state,
                                     TimelineId timeline_id,
                                     int64_t position,
                                     LayerId layer_id);

FfiResultVoid req_cmd_add_layer(CommandQueue *ptr_queue,
                                TimelineId timeline_id,
                                bool has_parent,
                                LayerFolderId parent_folder_id,
                                bool has_insert_index,
                                uintptr_t insert_index,
                                FfiStringView name);

FfiResultVoid req_cmd_add_folder(CommandQueue *ptr_queue,
                                 TimelineId timeline_id,
                                 bool has_parent,
                                 LayerFolderId parent_folder_id,
                                 bool has_insert_index,
                                 uintptr_t insert_index,
                                 FfiStringView name);

uintptr_t debug_streams_get_resources_arr_size(const ClientStateHandle *ptr_state);

bool debug_streams_write_resources_arr(const ClientStateHandle *ptr_state,
                                       uint32_t *ptr_out_arr,
                                       uintptr_t safety_size);

uintptr_t debug_streams_get_loaded_streams_sec_arr_size(const ClientStateHandle *ptr_state,
                                                        uint32_t resource_id);

bool debug_streams_write_loaded_streams_sec_arr(const ClientStateHandle *ptr_state,
                                                uint32_t resource_id,
                                                double *ptr_out_arr,
                                                uintptr_t safety_size);

CFieldValue *esotereel_field_value_export(const FieldValue *value);

void esotereel_field_value_free(CFieldValue *value);

FfiResultVoid internal_server_start(const ClientStateHandle *ptr_state,
                                    FfiStringView addr,
                                    OnServerReadyCFn on_server_ready,
                                    FfiStringView std_plugin_dir,
                                    FfiStringView working_dir);

void init_rust_logger(LogOutCStrFn callback);

void set_log_level(FfiStringView target, CLogLevel level);

const Timeline *project_get_timeline(const Option<Project> *ptr, TimelineId id);

uintptr_t project_get_timeline_count(const Option<Project> *ptr);

ClipId clip_get_id(const Clip *ptr);

TimelineTick clip_get_position(const Clip *ptr);

TimelineTick clip_get_duration(const Clip *ptr);

CClipBindingValueResult clip_get_property_value(const Clip *ptr, FfiStringView key);

FfiPropertySchemaArrayResult clip_get_all_fields(const ClientStateHandle *ptr_state,
                                                 const Clip *ptr_clip);

FfiPropertySchemaArrayResult clip_get_common_fields(const ClientStateHandle *ptr_state,
                                                    const Clip *const *ptr_clips,
                                                    uintptr_t num_clips);

FfiStringArrayResult clip_get_categories(const ClientStateHandle *ptr_state, const Clip *ptr);

FfiResultVoid clip_set_property_value(CommandQueue *ptr_queue,
                                      TimelineId timeline_id,
                                      ClipId clip_id,
                                      FfiStringView key,
                                      CClipBindingValue value);

WrapperErrorCode render_rows_build(const Option<Project> *project,
                                   const Timeline *timeline,
                                   const uint64_t *open_ids_ptr,
                                   uintptr_t open_ids_len,
                                   const uint64_t *open_folder_ids_ptr,
                                   uintptr_t open_folder_ids_len,
                                   RenderRowsResult **out);

void render_rows_free(RenderRowsResult *ptr);

WrapperErrorCode render_rows_get_rows(const RenderRowsResult *ptr,
                                      const FfiLayerRow **out_ptr,
                                      uintptr_t *out_len);

WrapperErrorCode render_rows_get_clips(const RenderRowsResult *ptr,
                                       const ClipRenderInfo **out_ptr,
                                       uintptr_t *out_len);

FfiResult<const Clip*> layer_find_clip_at_frame(const Layer *layer_ptr,
                                                const Timeline *timeline_ptr,
                                                int64_t frame);

uintptr_t layer_get_clips_count(const Layer *ptr);

FfiResult<FfiStringView> layer_get_name(const Layer *ptr);

FfiResult<FfiStringView> layer_folder_get_name(const LayerFolder *ptr);

FfiResult<const Clip*> layer_get_clip_at_index(const Layer *layer_ptr,
                                               const Timeline *timeline_ptr,
                                               uintptr_t index);

FfiResult<const Clip*> layer_get_clip_at_position(const Layer *layer_ptr,
                                                  const Timeline *timeline_ptr,
                                                  int64_t position);

WrapperErrorCode timeline_find_clip_by_id(const Timeline *ptr,
                                          ClipId clip_id,
                                          const Clip **out_clip,
                                          LayerId *out_layer_id);

bool timeline_can_place_clip_at(const Timeline *ptr,
                                uint64_t layer_id,
                                int64_t position,
                                int64_t duration,
                                const uint64_t *exclude_ids_ptr,
                                uintptr_t exclude_ids_len);

double timeline_get_fps(const Timeline *ptr);

const Layer *timeline_get_layer_by_id(const Timeline *ptr, LayerId layer_id);

const LayerFolder *timeline_get_folder_by_id(const Timeline *ptr, LayerFolderId folder_id);

const Layer *timeline_get_layer_by_execution_index(const Timeline *ptr, uintptr_t index);

uintptr_t timeline_get_layers_count(const Timeline *ptr);

uint64_t timeline_get_layer_id_at_execution_index(const Timeline *ptr, uintptr_t index);

WrapperErrorCode wgpuutil_render_frame_offscreen(WGpuUtil *ptr_wgpu,
                                                 OffscreenTarget *ptr_offscreen,
                                                 const ClientStateHandle *ptr_state,
                                                 const CameraInfo *ptr_camera_info,
                                                 TimelineId timeline_id,
                                                 int64_t current_frame,
                                                 uint8_t **out_data,
                                                 uintptr_t *out_len,
                                                 uint32_t *out_width,
                                                 uint32_t *out_height);

FfiResultVoid req_test(const ClientStateHandle *ptr_state);

FfiResultVoid req_new_project(const ClientStateHandle *ptr_state);

FfiResultVoid req_fetch_frame(const ClientStateHandle *ptr_state,
                              TimelineId timeline_id,
                              TimelineTick current_frame,
                              TimelineTick visible_range_start,
                              TimelineTick visible_range_end);

FfiResultVoid req_project_log(const ClientStateHandle *ptr_state);

FfiResultVoid req_load_stream(const ClientStateHandle *ptr_state, FfiStringView path);

FfiPropertySchemaArrayResult settings_get_all_fields(const ClientStateHandle *ptr_state);

CFieldValueResult settings_get_value(const ClientStateHandle *ptr_state, FfiStringView key);

FfiResultVoid settings_set_value(const ClientStateHandle *ptr_state,
                                 FfiStringView key,
                                 CFieldValue value);

FfiStringArrayResult settings_get_categories(const ClientStateHandle *ptr_state);

ClientStateNewResult client_state_new(GuiCallbacks callbacks,
                                      FfiStringView std_plugin_dir,
                                      FfiStringView working_dir);

FfiResultVoid client_state_bootstrap(const ClientStateHandle *ptr_state);

FfiResultVoid client_state_network_run(const ClientStateHandle *ptr_state, FfiStringView addr);

FfiResultVoid client_state_drop(const ClientStateHandle *ptr_state);

ProjectLockReadResult client_state_project_lock_read(const ClientStateHandle *ptr_state);

/// ガードをドロップ（アンロック）する関数
FfiResultVoid client_state_project_unlock_read(const void *guard_ptr);

ProjectFromGuardResult project_guard_get_project_from_guard(const void *guard_ptr);

FfiResultVoid client_state_log_directories_info(const ClientStateHandle *ptr_state);

/// Frees a string that was allocated by Rust and returned via OwnedString
void owned_string_free(FfiOwnedString str);

FfiOwnedString owned_string_new(FfiStringView str);

FfiToolbarButtonArrayResult toolbar_get_buttons(const ClientStateHandle *ptr_state,
                                                FfiStringView target);

FfiResultVoid toolbar_set_layout(const ClientStateHandle *ptr_state,
                                 FfiStringView target,
                                 FfiStringView ids_toml_array);

FfiResultVoid toolbar_handle_action(const ClientStateHandle *ptr_state, FfiStringView button_id);

WGpuUtilNewResult wgpuutil_new(uint32_t width, uint32_t height);

FfiResultVoid wgpuutil_drop(WGpuUtil *ptr);

OffscreenTargetNewResult offscreen_target_new(WGpuUtil *ptr_wgpu, uint32_t width, uint32_t height);

FfiResultVoid offscreen_target_drop(OffscreenTarget *ptr);

/// バッファ解放。呼び出し元が正しい(ptr, len)ペアを渡す前提の単純な解放処理であり、
/// 失敗しうる操作ではないため FfiResult 化はせず元のまま据え置き。
void wgpuutil_free_buffer(uint8_t *ptr,
                          uintptr_t len);

}  // extern "C"

}  // namespace esotereel_gui_helper
