#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <QVector3D>
#include <QMatrix4x4>
#include <cstdint>

namespace esotereel_gui_helper {

enum class WrapperErrorCode {
  Ok = 0,
  NullPtr = 1,
  NotFound = 2,
  Error = 3,
  Panic = 4,
};

enum class CLogLevel : uint8_t {
  Off,
  Error,
  Warn,
  Info,
  Debug,
  Trace,
};

enum class Direction {
  Front,
  Back,
  Top,
  Bottom,
  Left,
  Right,
};

enum class PlatformKind : uint32_t {
  Unknown = 0,
  Xcb = 1,
  Wayland = 2,
  Win32 = 3,
  AppKit = 4,
};

struct ClientNetworkHandler;

struct Clip;

/// レイヤーには特定の役割を持たせない(Video/Audio/Effectで型を分けない)。
/// children があれば Folder として振る舞う。実行時にフラット化するかは
/// executor 側の責務で、データ構造上は葉レイヤーと区別しない。
struct Layer;

struct OffscreenTarget;

struct Project;

struct RenderRowsResult;

struct Timeline;

struct WGpuUtil;

using TimelineId = uint64_t;

struct GuiCallbacks {
  void (*on_test)();
  void (*mark_dirty_timeline)(TimelineId timeline_type);
};

using OnConnectedFn = void(*)();

using LayerId = uint64_t;

struct StringView {
  const uint8_t *ptr;
  uintptr_t len;
};

using OnServerReadyCFn = void(*)(bool, StringView);

using LogOutCStrFn = void(*)(uintptr_t level, StringView target, StringView msg);

struct FfiLayerRow {
  LayerId layer_id;
  TimelineId timeline_id;
  uint32_t depth;
  bool is_folder;
  bool is_folder_open;
  uint32_t clip_start;
  uint32_t clip_count;
};

struct ClipRenderInfo {
  uint64_t clip_id;
  int64_t abs_frame;
  int64_t duration;
  bool is_composite;
  bool is_open;
};

struct CameraInfo {
  QVector3D position;
  QVector3D rotation;
  bool is_orthographic;
  Direction orthographic_direction;
  float scale_factor;
  float fov;
};

using TimelineTick = int64_t;

struct NativeWindowHandle {
  PlatformKind kind;
  void *window_ptr;
  void *display_ptr;
};

using ClipId = uint64_t;

using ScriptId = uint64_t;

extern "C" {

const char *get_last_err_msg();

void init();

void set_gui_callbacks(GuiCallbacks callbacks);

void set_on_connected_callback(OnConnectedFn callback);

WrapperErrorCode req_cmd_clip_move_mul(const ClientNetworkHandler *ptr_network,
                                       TimelineId timeline_id,
                                       const uint64_t *ptr,
                                       uintptr_t len,
                                       int64_t position_moved,
                                       int64_t duration_added,
                                       intptr_t layer_moved);

WrapperErrorCode req_cmd_add_clip_dummy(const ClientNetworkHandler *ptr_network,
                                        TimelineId timeline_id,
                                        int64_t position,
                                        LayerId layer_id);

WrapperErrorCode req_cmd_add_layer(const ClientNetworkHandler *ptr_network,
                                   TimelineId timeline_id,
                                   bool has_parent,
                                   LayerId parent_layer_id,
                                   bool has_insert_index,
                                   uintptr_t insert_index,
                                   StringView name,
                                   bool is_folder);

uintptr_t debug_streams_get_resources_arr_size(const ClientNetworkHandler *ptr_network);

bool debug_streams_write_resources_arr(const ClientNetworkHandler *ptr_network,
                                       uint32_t *ptr_out_arr,
                                       uintptr_t safety_size);

uintptr_t debug_streams_get_loaded_streams_sec_arr_size(const ClientNetworkHandler *ptr_network,
                                                        uint32_t resource_id);

bool debug_streams_write_loaded_streams_sec_arr(const ClientNetworkHandler *ptr_network,
                                                uint32_t resource_id,
                                                double *ptr_out_arr,
                                                uintptr_t safety_size);

WrapperErrorCode internal_server_start(const ClientNetworkHandler *network_ptr,
                                       StringView addr,
                                       OnServerReadyCFn on_server_ready,
                                       StringView std_plugin_dir,
                                       StringView working_dir);

void init_rust_logger(LogOutCStrFn callback);

void set_log_level(StringView target, CLogLevel level);

WrapperErrorCode client_network_handler_run(const ClientNetworkHandler *ptr, StringView addr);

WrapperErrorCode client_network_handler_new(const ClientNetworkHandler **out,
                                            StringView std_plugin_dir,
                                            StringView working_dir);

WrapperErrorCode client_network_handler_bootstrap(const ClientNetworkHandler *ptr);

WrapperErrorCode client_network_handler_drop(const ClientNetworkHandler *ptr);

WrapperErrorCode client_network_handler_app_state_project_lock_read(const ClientNetworkHandler *ptr,
                                                                    const void **out_guard);

/// ガードをドロップ（アンロック）する関数
WrapperErrorCode client_network_handler_app_state_project_unlock_read(const void *guard_ptr);

/// ガードからprojectポインタを取得する関数
WrapperErrorCode project_guard_get_project_from_guard(const void *guard_ptr,
                                                      const Project **out_project);

WrapperErrorCode client_network_handler_log_directories_info(const ClientNetworkHandler *ptr);

const Timeline *project_get_timeline(const Project *ptr, TimelineId id);

uintptr_t project_get_timeline_count(const Project *ptr);

uint64_t clip_get_id(const Clip *ptr);

int64_t clip_get_position(const Clip *ptr);

int64_t clip_get_duration(const Clip *ptr);

WrapperErrorCode render_rows_build(const Project *project,
                                   const Timeline *timeline,
                                   const uint64_t *open_ids_ptr,
                                   uintptr_t open_ids_len,
                                   const uint64_t *open_folder_ids_ptr,
                                   uintptr_t open_folder_ids_len,
                                   RenderRowsResult **out);

void render_rows_free(RenderRowsResult *ptr);

WrapperErrorCode render_rows_get_rows(const RenderRowsResult *ptr,
                                      const FfiLayerRow **out_ptr,
                                      uintptr_t *out_len);

WrapperErrorCode render_rows_get_clips(const RenderRowsResult *ptr,
                                       const ClipRenderInfo **out_ptr,
                                       uintptr_t *out_len);

void project_debug_log(const Project *ptr);

WrapperErrorCode layer_find_clip_at_frame(const Layer *layer_ptr,
                                          const Timeline *timeline_ptr,
                                          int64_t frame,
                                          const Clip **out);

uintptr_t layer_get_clips_count(const Layer *ptr);

StringView layer_get_name(const Layer *ptr);

WrapperErrorCode layer_get_clip_at_index(const Layer *layer_ptr,
                                         const Timeline *timeline_ptr,
                                         uintptr_t index,
                                         const Clip **out);

WrapperErrorCode layer_get_clip_at_position(const Layer *layer_ptr,
                                            const Timeline *timeline_ptr,
                                            int64_t position,
                                            const Clip **out);

const Layer *timeline_get_layer_by_order(const Timeline *ptr, uint32_t order);

const Layer *timeline_get_layer_by_sorted_idx(const Timeline *ptr, uint32_t index);

uintptr_t timeline_get_layers_count(const Timeline *ptr);

WrapperErrorCode timeline_find_clip_by_id(const Timeline *ptr,
                                          uint64_t clip_id,
                                          const Clip **out_clip,
                                          uint64_t *out_layer_id);

bool timeline_can_place_clip_at(const Timeline *ptr,
                                uint64_t layer_id,
                                int64_t position,
                                int64_t duration,
                                const uint64_t *exclude_ids_ptr,
                                uintptr_t exclude_ids_len);

double timeline_get_fps(const Timeline *ptr);

const Layer *timeline_get_layer_by_id(const Timeline *ptr, uint64_t layer_id);

uint64_t timeline_get_layer_id_at_root_index(const Timeline *ptr, uintptr_t index);

WrapperErrorCode wgpuutil_render_frame_offscreen(WGpuUtil *ptr_wgpu,
                                                 OffscreenTarget *ptr_offscreen,
                                                 const ClientNetworkHandler *ptr_network,
                                                 const CameraInfo *ptr_camera_info,
                                                 TimelineId timeline_id,
                                                 int64_t current_frame,
                                                 uint8_t **out_data,
                                                 uintptr_t *out_len,
                                                 uint32_t *out_width,
                                                 uint32_t *out_height);

void req_test(const ClientNetworkHandler *ptr_network);

void req_new_project(const ClientNetworkHandler *ptr_network);

WrapperErrorCode req_fetch_frame(const ClientNetworkHandler *ptr_network,
                                 TimelineId timeline_id,
                                 TimelineTick current_frame,
                                 TimelineTick visible_range_start,
                                 TimelineTick visible_range_end);

void req_project_log(const ClientNetworkHandler *ptr_network);

WrapperErrorCode req_load_stream(const ClientNetworkHandler *ptr_network, StringView path);

WrapperErrorCode wgpuutil_new(uint32_t width, uint32_t height, WGpuUtil **out);

WrapperErrorCode wgpuutil_drop(WGpuUtil *ptr);

WrapperErrorCode offscreen_target_new(WGpuUtil *ptr_wgpu,
                                      uint32_t width,
                                      uint32_t height,
                                      OffscreenTarget **out);

WrapperErrorCode offscreen_target_drop(OffscreenTarget *ptr);

void wgpuutil_free_buffer(uint8_t *ptr, uintptr_t len);

}  // extern "C"

}  // namespace esotereel_gui_helper
