#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
#include <QVector3D>
#include <QMatrix4x4>
#include <cstdint>

namespace esotereel_gui_helper {

enum class WrapperErrorCode {
  Ok = 0,
  NullPtr = 1,
  NotFound = 2,
  Error = 3,
  Panic = 4,
};

enum class PlatformKind : uint32_t {
  Unknown = 0,
  Xcb = 1,
  Wayland = 2,
  Win32 = 3,
  AppKit = 4,
};

enum class Direction {
  Front,
  Back,
  Top,
  Bottom,
  Left,
  Right,
};

struct ClientNetworkHandler;

struct Clip;

struct ClipIterator;

struct Layer;

struct Project;

struct RenderRowsResult;

struct Timeline;

struct WGpuUtil;

struct GuiCallbacks {
  void (*on_test)();
  void (*mark_dirty_timeline)(uintptr_t timeline_type);
};

using OnConnectedFn = void(*)();

struct StringView {
  const uint8_t *ptr;
  uintptr_t len;
};

using OnServerReadyFn = void(*)(bool);

using LogOutCStrFn = void(*)(uintptr_t level, StringView target, StringView msg);

struct FfiLayerRow {
  uint32_t layer_order;
  uint32_t depth;
  uint32_t clip_start;
  uint32_t clip_count;
};

struct ClipRenderInfo {
  uint64_t clip_id;
  int64_t abs_frame;
  int64_t duration;
  bool is_composite;
  bool is_open;
};

struct NativeWindowHandle {
  PlatformKind kind;
  void *window_ptr;
  void *display_ptr;
};

struct CameraInfo {
  QVector3D position;
  QVector3D rotation;
  bool is_orthographic;
  Direction orthographic_direction;
  float scale_factor;
  float fov;
};

extern "C" {

const char *get_last_err_msg();

void init();

void set_gui_callbacks(GuiCallbacks callbacks);

void set_on_connected_callback(OnConnectedFn callback);

WrapperErrorCode req_cmd_clip_move_mul(const ClientNetworkHandler *ptr_network,
                                       uintptr_t timeline_idx,
                                       const uint64_t *ptr,
                                       uintptr_t len,
                                       int64_t position_moved,
                                       int64_t duration_added,
                                       intptr_t layer_moved);

WrapperErrorCode req_cmd_add_clip_dummy(const ClientNetworkHandler *ptr_network,
                                        uintptr_t timeline_idx,
                                        int64_t position,
                                        uint32_t layer_order);

uintptr_t debug_streams_get_resources_arr_size(const ClientNetworkHandler *ptr_network);

bool debug_streams_write_resources_arr(const ClientNetworkHandler *ptr_network,
                                       uint32_t *ptr_out_arr,
                                       uintptr_t safety_size);

uintptr_t debug_streams_get_loaded_streams_sec_arr_size(const ClientNetworkHandler *ptr_network,
                                                        uint32_t resource_id);

bool debug_streams_write_loaded_streams_sec_arr(const ClientNetworkHandler *ptr_network,
                                                uint32_t resource_id,
                                                double *ptr_out_arr,
                                                uintptr_t safety_size);

WrapperErrorCode internal_server_start(StringView addr, OnServerReadyFn on_server_ready);

void init_rust_logger(LogOutCStrFn callback);

WrapperErrorCode client_network_handler_run(const ClientNetworkHandler *ptr, StringView addr);

WrapperErrorCode client_network_handler_new(const ClientNetworkHandler **out);

WrapperErrorCode client_network_handler_drop(const ClientNetworkHandler *ptr);

WrapperErrorCode client_network_handler_app_state_project_lock_read(const ClientNetworkHandler *ptr,
                                                                    const void **out);

WrapperErrorCode client_network_handler_app_state_project_unlock_read(const void *guard_ptr);

const Timeline *project_get_timeline(const Project *ptr, uintptr_t id);

uintptr_t project_get_timeline_count(const Project *ptr);

WrapperErrorCode project_guard_get_project_from_guard(const void *guard_ptr, const Project **out);

uint64_t clip_get_id(const Clip *ptr);

int64_t clip_get_position(const Clip *ptr);

int64_t clip_get_duration(const Clip *ptr);

WrapperErrorCode render_rows_build(const Project *project,
                                   const Timeline *timeline,
                                   const uint64_t *open_ids_ptr,
                                   uintptr_t open_ids_len,
                                   RenderRowsResult **out);

void render_rows_free(RenderRowsResult *ptr);

WrapperErrorCode render_rows_get_rows(const RenderRowsResult *ptr,
                                      const FfiLayerRow **out_ptr,
                                      uintptr_t *out_len);

WrapperErrorCode render_rows_get_clips(const RenderRowsResult *ptr,
                                       const ClipRenderInfo **out_ptr,
                                       uintptr_t *out_len);

void project_debug_log(const Project *ptr);

WrapperErrorCode layer_find_clip_at_frame(const Layer *ptr, int64_t frame, const Clip **out);

uintptr_t layer_get_clips_count(const Layer *ptr);

StringView layer_get_name(const Layer *ptr);

WrapperErrorCode layer_clips_begin(const Layer *layer, ClipIterator **out);

WrapperErrorCode layer_clips_in_range_begin(const Layer *layer,
                                            int64_t start,
                                            int64_t end,
                                            ClipIterator **out);

WrapperErrorCode clip_iter_next(ClipIterator *iter_ptr, const Clip **out);

WrapperErrorCode clip_iter_free(ClipIterator *iter);

const Layer *timeline_get_layer_by_order(const Timeline *ptr, uint32_t order);

const Layer *timeline_get_layer_by_sorted_idx(const Timeline *ptr, uint32_t index);

uintptr_t timeline_get_layers_count(const Timeline *ptr);

WrapperErrorCode timeline_find_clip_by_id(const Timeline *ptr,
                                          uint64_t clip_id,
                                          const Clip **out_clip,
                                          uint32_t *out_layer_idx);

bool timeline_can_place_clip_at(const Timeline *ptr,
                                uint32_t layer_order,
                                int64_t position,
                                int64_t duration,
                                const uint64_t *exclude_ids_ptr,
                                uintptr_t exclude_ids_len);

double timeline_get_fps(const Timeline *ptr);

StringView wgpuutil_init_surface(NativeWindowHandle handle,
                                 uint32_t width,
                                 uint32_t height,
                                 WGpuUtil **out);

StringView wgpuutil_drop(WGpuUtil *ptr);

/// wgpu内部でパニック(バリデーションエラー等)が発生した後のWGpuUtilは、
/// 内部状態(ロック中のデータ構造やGPUリソースの参照カウントなど)が
/// 中途半端に書き換わったまま巻き戻っている可能性があり、
/// 通常のDrop(=wgpuutil_drop)を走らせるとその破損した状態を読みに行って
/// 二次的なクラッシュ(heap-use-after-freeなど)を引き起こしうる。
///
/// そのためパニックをcatchした後は、このwgpuutil_leakで
/// **Dropを一切走らせずに**ポインタだけ手放す(意図的なメモリリーク)。
/// リソースは解放されないままになるが、破損した状態への追撃読み書きよりは
/// 安全側に倒した選択。
void wgpuutil_leak(WGpuUtil *ptr);

StringView wgpuutil_update_surface(WGpuUtil *ptr, NativeWindowHandle handle);

StringView wgpuutil_update_size(WGpuUtil *ptr, uint32_t width, uint32_t height);

StringView wgpuutil_render_frame(WGpuUtil *ptr_wgpu,
                                 const ClientNetworkHandler *ptr_network,
                                 const Timeline *ptr_timeline,
                                 const CameraInfo *ptr_camera_info,
                                 int64_t current_frame);

void req_test(const ClientNetworkHandler *ptr_network);

void req_new_project(const ClientNetworkHandler *ptr_network);

WrapperErrorCode req_load_stream(const ClientNetworkHandler *ptr_network, StringView path);

}  // extern "C"

}  // namespace esotereel_gui_helper
